version: '3.8'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      - redis
    ports:
      - "5007:5007"  # Map Flask app port to the host

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    depends_on:
      - redis
    deploy:
      replicas: 5  # Number of subscriber instances
      restart_policy:
        condition: on-failure